package com.financialtransaction.enums;

public enum AuditEventType {

    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,

    DEBIT_INITIATED,
    DEBIT_SUCCESS,
    DEBIT_FAILED,

    CREDIT_INITIATED,
    CREDIT_SUCCESS,
    CREDIT_FAILED,

    TRANSFER_INITIATED,
    TRANSFER_SUCCESS,
    TRANSFER_FAILED,

    TRANSACTION_REVERSED,
    FRAUD_DETECTED,

    LOGIN_SUCCESS,
    LOGIN_FAILED
}